# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with a Node.js image
FROM node:22.12-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN --mount=type=cache,target=/root/.npm npm install --ignore-scripts

# Copy the rest of the application code
COPY src src
COPY tsconfig.json .

# Build the project
RUN npm run build

# Use a smaller image for the production environment
FROM node:22-alpine AS release

# Set the working directory
WORKDIR /app

# Copy the built application and node modules from the builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Install production dependencies only
RUN npm ci --ignore-scripts --omit=dev

# Set the environment variable
ENV NODE_ENV=production

# Entry point for the Docker container
ENTRYPOINT ["node", "dist/index.js"]